In [13]:
import numpy as np

In [2]:
import pandas as pd
import matplotlib as plt

In [3]:
import seaborn as sns

Functions


In [7]:
def student(name,age):
    print(name,age)

student("kunal",25)

kunal 25


In [8]:
import math 

In [9]:
import math 
from math import sqrt

In [10]:
sqrt(5)

2.23606797749979

#NUMPY

pip install numpy

In [14]:
#creating 1D array

x= np.array([1,2,3])

#creating 2D

y = np.array([[1,2],[3,4]])

#Creating 3D

z = np.array([[[1,2],[3,4],[5,6],[7,8]]])

print(x)
print(y)
print(z)

[1 2 3]
[[1 2]
 [3 4]]
[[[1 2]
  [3 4]
  [5 6]
  [7 8]]]


#Pandas


s= pd.Series([10,20,30,50],name = "Number")

In [15]:
s = pd.Series([10,20,30,40],name = "Number")

In [ ]:
df = pd.DataFrame(data)
#for converting the dataFrame


In [16]:
data = {
    'Name':['kunal','ji'],
    'Age':[25,10],
    'City':['Al','ja'],
    'Salary':[20000,522200]
}
print(data)

{'Name': ['kunal', 'ji'], 'Age': [25, 10], 'City': ['Al', 'ja'], 'Salary': [20000, 522200]}


In [17]:
data = {
    'Name':['kunal','ji'],
    'Age':[25,10],
    'City':['Al','ja'],
    'Salary':[20000,522200]
}
print(data)

{'Name': ['kunal', 'ji'], 'Age': [25, 10], 'City': ['Al', 'ja'], 'Salary': [20000, 522200]}


In [18]:
data = {
    'Name':['kunal','ji'],
    'Age':[25,10],
    'City':['Al','ja'],
    'Salary':[20000,522200]
}
print(data)

df = pd.DataFrame(data)

print(df)

{'Name': ['kunal', 'ji'], 'Age': [25, 10], 'City': ['Al', 'ja'], 'Salary': [20000, 522200]}
    Name  Age City  Salary
0  kunal   25   Al   20000
1     ji   10   ja  522200


In [19]:

data = {
    'Name':['kunal','ji'],
    'Age':[25],
    'City':['Al','ja'],
    'Salary':[20000,522200]
}
print(data)

df = pd.DataFrame(data)

print(df)

{'Name': ['kunal', 'ji'], 'Age': [25], 'City': ['Al', 'ja'], 'Salary': [20000, 522200]}


ValueError: All arrays must be of the same length

In [21]:
df = pd.read_csv("https://www.kaggle.com/datasets/mdsultanulislamovi/student-stress-monitoring-datasets?select=StressLevelDataset.csv")

ParserError: Error tokenizing data. C error: Expected 1 fields in line 9, saw 2


In [23]:
df = pd.read_csv(r"C:\Users\PC\Downloads\archive\Stress_Dataset.csv")

In [24]:
df

Gender  Age  Have you recently experienced stress in your life?  \
0         0   20                                                  3    
1         0   20                                                  2    
2         0   20                                                  5    
3         1   20                                                  3    
4         0   20                                                  3    
..      ...  ...                                                ...    
838       0   21                                                  3    
839       1   19                                                  3    
840       1   19                                                  4    
841       0   20                                                  5    
842       0   19                                                  4    

     Have you noticed a rapid heartbeat or palpitations?  \
0                                                    4     
1                                                    3     
2                                                    4     
3                                                    4     
4                                                    3     
..                                                 ...     
838                                                  4     
839                                                  2     
840                                                  4     
841                                                  4     
842                                                  3     

     Have you been dealing with anxiety or tension recently?  \
0                                                    2         
1                                                    2         
2                                                    2         
3                                                    3         
4                                                    3         
..                                                 ...         
838                                                  2         
839                                                  1         
840                                                  3         
841                                                  3         
842                                                  1         

     Do you face any sleep problems or difficulties falling asleep?  \
0                                                    5                
1                                                    1                
2                                                    2                
3                                                    2                
4                                                    2                
..                                                 ...                
838                                                  3                
839                                                  2                
840                                                  4                
841                                                  4                
842                                                  3                

     Have you been dealing with anxiety or tension recently?.1  \
0                                                    1           
1                                                    1           
2                                                    1           
3                                                    2           
4                                                    2           
..                                                 ...           
838                                                  5           
839                                                  2           
840                                                  3           
841                                                  3           
842                                                  2           

    

In [25]:
df.head()

Gender  Age  Have you recently experienced stress in your life?  \
0       0   20                                                  3    
1       0   20                                                  2    
2       0   20                                                  5    
3       1   20                                                  3    
4       0   20                                                  3    

   Have you noticed a rapid heartbeat or palpitations?  \
0                                                  4     
1                                                  3     
2                                                  4     
3                                                  4     
4                                                  3     

   Have you been dealing with anxiety or tension recently?  \
0                                                  2         
1                                                  2         
2                                                  2         
3                                                  3         
4                                                  3         

   Do you face any sleep problems or difficulties falling asleep?  \
0                                                  5                
1                                                  1                
2                                                  2                
3                                                  2                
4                                                  2                

   Have you been dealing with anxiety or tension recently?.1  \
0                                                  1           
1                                                  1           
2                                                  1           
3                                                  2           
4                                                  2           

   Have you been getting headaches more often than usual?  \
0                                                  2        
1                                                  1        
2                                                  3        
3                                                  3        
4                                                  4        

   Do you get irritated easily?  \
0                             1   
1                             1   
2                             4   
3                             4   
4                             4   

   Do you have trouble concentrating on your academic tasks?  ...  \
0                                                  2          ...   
1                                                  4          ...   
2                                                  2          ...   
3                                                  3          ...   
4                                                  4          ...   

   Are you facing any difficulties with your professors or instructors?  \
0                                                  3                      
1                                                  3                      
2                                                  2                      
3                                                  1                      
4                                                  2                      

   Is your working environment unpleasant or stressful?  \
0                                                  1      
1                                                  2      
2                                                  2      
3                                                  1      
4                                                  3      

   Do you struggle to find time for relaxation and leisure activities?  \
0                                                  4                     
1                                                  1                     
2                                      