#Task 1


In [10]:
import numpy as np
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr2 = np.multiply(arr,2)
print("Before Multipy:\n",arr)
print("After Multiply:\n",arr2)

Before Multipy:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
After Multiply:
 [[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]


In [6]:
print("Before Multipy:\n",arr)

Before Multipy:
 [[[1 2 3]
  [4 5 6]
  [7 8 9]]]


In [7]:
print("After Multiply:\n",arr2)

After Multiply:
 [[[ 2  4  6]
  [ 8 10 12]
  [14 16 18]]]


#Task2

In [17]:
import pandas as pd

data = {
    'product_name': ['Product A', 'Product B', 'Product C', 'Product D'],
    'price': [10.99, 15.49, 7.99, 12.49],
    'quantity': [60, 40, 200, 30]
}

df = pd.DataFrame(data)
print(df)

  product_name  price  quantity
0    Product A  10.99        60
1    Product B  15.49        40
2    Product C   7.99       200
3    Product D  12.49        30


#Task3


In [21]:
datafilter = df[df['quantity'] > 50]
print(datafilter)

  product_name  price  quantity
0    Product A  10.99        60
2    Product C   7.99       200
